### ISSUE TITLE
Possible outdated package in ska3-core for Windows

### ISSUE THREAD

**Issue by javierggt** [sot/skare3#1156]
@jskrist pointed out in ska_helpers/issues/44:

- the git command is reverting/ignoring/overwriting the permissions of the index file. I set it to read only, and the command writes to it anyway.
- I cannot use many (maybe any) of the commands in Library\usr\bin\ directory of the python environment, which includes commands like chmod, which, whoami. all of these commands throw an error related to issues with locale_ctype_ptr missing from a dll (which is sometimes reported as msys_intl_8.dll).

and

> my suspicion is that these executables and dlls come from the python package msys2-conda-epoch, which is 7 years old, and may not be compatible any longer.

The question is whether that package is outdated, why it is being pulled in, and what alternatives are there.

**Comment by jeanconn** [comment]
I'll redo my git clone test that seemed to work on matlab testing (I think it worked).

**Comment by javierggt** [comment]
The msys2-conda-epoch is pulled in by `conda-build`.

One possibility is to not install `conda-build`. I think `skare3_tools` is the only one that uses it.

While checking this, I noticed that conda and mamba give different solutions. If I install the environment with mamba, it pulls `msys2-conda-epoch=20230914` (from a few months ago). Maybe this one would cause no issues.

**Comment by jeanconn** [comment]
Either way I don't _think_ we have a need for conda-build to be installed as part of ska3-core on windows.  I would just see us needing it in the build environment.

**Comment by javierggt** [comment]
Not installing conda-build is a bit more of work, because I use it heavily when I generate the `meta.yaml` for ska3-core. It is possible though.

What I did is to tweak the process so ska3-core 2024.1 (which will become ska3-matlab 2024.2) will include `m2-conda-epoch=20230914`.

**Comment by javierggt** [comment]
I am marking #1282 as a fix for this issue.

Strictly speaking, @jskrist, can you check if ska_helpers/issues/44 is fixed with this version? (that issue was not fixed, it was just closed because of a workaround).

**Comment by jeanconn** [comment]
For [ska_helpers/issues/44](https://github.com/sot/ska_helpers/issues/44) I thought that touching the index was just something git did and not a function of the msys2 stuff (https://github.com/sot/ska_helpers/issues/44#issuecomment-1640936909)

**Comment by javierggt** [comment]
ah, maybe. Then the check will be to verify that the apps in `Library\usr\bin` can be used.

**Comment by jskrist** [comment]
I'm assuming I get this as part of ska3-matlab version 2024.2rc3?  If so, I'll be testing that out today and let you know what I find.

**Comment by javierggt** [comment]
yes, that is in 2024.2rc3

**Comment by jskrist** [comment]
from what I can tell, ska3-matlab 2024.2rc3 is broadly compatible with the MATLAB tools.  The interface code needs to be recompiled to use the latest libraries, and there may need to be some updates to the fot-matlab package (this new version causes a bunch of windows to appear when creating parallel processes, which is undesirable).

I did check a few of the executables in the `Library\usr\bin` and `Library\bin` folders, and they seem to be working for me, and in my limited testing, I haven't seen any changes to the .git index files for the chandra models directories, although there were other changes that switched to using a different method which avoided the modification of these files previously so I'm not sure if simply using the MATLAB Tools is enough to actually test if that issue is resolved.

**Comment by jskrist** [comment]
Update on https://github.com/sot/ska_helpers/issues/44: I ran through the reproduction steps in the issue, and have found that it still results in the index file being touched.  So this is still an issue.
