### ISSUE TITLE
Make skare3 work with modern conda installer / environments

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#170]
Modern conda should be able to install ska3-flight fine; initial tests showed that maybe this needs core-pkg-repo for some old packages that are no longer baked into the default channels for new versions of conda.

**Comment by granttremblay** [comment]
Hi @jeanconn! Before I start bugging you re: this potentially trivial question, I wanted to make sure my current issue wasn't related to this one. 

The Ska3 install on my macOS machine (which is running an up-to-date conda + anaconda environment) works fine. 

When I try to install on my Linux 64 (Ubuntu 19.04) machine, however - again with a totally up-to-date conda - I get this. Just trying to parse whether this issue is related! Thanks! 
![Screenshot from 2019-08-05 11-20-38](https://user-images.githubusercontent.com/2238418/62475636-6bd8c080-b773-11e9-90ac-6494f2615ff0.png)

**Comment by jeanconn** [comment]
Thanks @granttremblay !  Can you get me your conda version and the channels in your current .condarc (if any)?

**Comment by granttremblay** [comment]
No channels in my .condarc! Conda version is 4.7.10

![Screenshot from 2019-08-05 11-53-01](https://user-images.githubusercontent.com/2238418/62477775-a93f4d00-b777-11e9-8dac-7fd5faf34dfd.png)

**Comment by jeanconn** [comment]
Thanks!  Will test with that configuration.  My initial thought is that adding our archive of core pkgs might work around a missing old package dependence (so worth trying if you have a sec but untested on my end just yet).

```
conda create --channel $ska3conda --channel ${ska3conda}/core-pkg-repo \
--name ska3 ska3-flight
```

**Comment by granttremblay** [comment]
Ooo, that worked, @jeanconn! Thank you! 
![Screenshot from 2019-08-05 12-01-50](https://user-images.githubusercontent.com/2238418/62478331-d4766c00-b778-11e9-8f83-42849a0cd1d7.png)

**Comment by jeanconn** [comment]
Great!  I'll most likely close this issue with a doc update to suggest that install process for now, but I will test on a few machines.

**Comment by jeanconn** [comment]
@granttremblay, as an aside, it is looking like I won't have time to test newer versions of conda with the ska3-flight packages, so we're going to call conda 4.3.21 the operationally-approved version and others as play-with-at-your-own-risk for now. But I'll still be updating our docs if needed. 

I also haven't had a chance to play with newer versions of conda to know if folks are going to *require* new versions for use with other tools or great new features.  If you have other drivers for using more modern conda, please feel free to throw them in this PR as comments.

**Comment by jzuhone** [comment]
I would argue that probably the most limiting restriction is not necessarily the conda version (though that is getting increasingly problematic) but having NumPy pinned at 1.12. For example, the stuff that Lina showed at the DAWG earlier this week requires a version of tensorflow that (at least for installing conda packages) requires a NumPy later than 1.12.

**Comment by jeanconn** [comment]
Yes, though I was more immediately concerned that not working with new versions of conda would prevent users from having useful different conda envs (including a ska3 one) working under the same installation... and that there was no real *reason* why more modern conda couldn't work.

The limiting restriction that we've got numpy pinned at 1.12 is at least due to a real restriction; we only have conda packages built on/for centos5 from continuum up to 1.12, and we're still supporting centos5 for the FOT work.  So we can either build all the more modern packages (numpy 1.16 and stack) ourselves for centos5 or wait out the upgrade to centos6 or 7.

We may be able to allow more ska3 packages to be installed standalone (so they could go into a more modern environment with tensorflow and modern numpy), but I'm not sure what that will buy us from a maintenance perspective; we can't really test them in the full ska unless we have all of the packages and versions locked down.

**Comment by taldcroft** [comment]
We are planning a major version update basically as soon as the FOT updates chimchim and cheru to CentOS-7.  Cheru was supposed to be done already.  Anyway, I noted the same issue about tensorflow and think the answer for "experimental" work like that is to break the configuration and install the latest.  In fact, for better or worse, `pip install tensorflow` does just that and upgrades numpy to the latest without asking.

Or better yet, this command installs everything without pinning any versions.  I tried this and it completed successfully.  NO guarantees that Ska3 works.
```
conda create -n ska3-dev -c $ska3conda ska3-dev
```

**Comment by jeanconn** [comment]
Regarding "without pinning any versions" there are a few versions that are hardcoded in some of the ska3 recipes right now that may basically *implicitly* pin.  But I'll be working on this for that ska3-dev use case and we can see how it goes.

**Comment by jzuhone** [comment]
If there is any work either of you want to offload onto me to make your lives easier for this let me know.

**Comment by taldcroft** [comment]
And FWIW, tensorflow seems well-supported in conda:

https://docs.anaconda.com/anaconda/user-guide/tasks/tensorflow/

**Comment by taldcroft** [comment]
FYI: https://www.anaconda.com/understanding-and-improving-condas-performance/

I ran into this issue accidentally.  Somehow my base conda got updated to the latest (4.7) and installing a new ska3 runtime failed miserably.  The fix here worked though, so 🎉 on that, but to make life easier I just downgraded back to 4.3.  OTOH the following is lightning fast (for solving) and requires a newer conda for the `--strict-channel-priority` flag:
```
conda create/install/update -c $ska3conda -c $ska3conda/core-pkg-repo \
  --strict-channel-priority ...
```

(This all started with a vague idea of making a docker container of ska3-core for CI testing of Ska3 packages on GitHub).

In other news, because of MATLAB compatibility issues there is good chance chimchim and cheru will be upgraded to CentOS-6, not 7.  :frown:, but we will still be able to drop CentOS-5 and 32-bit, and 6 is not yet EOL.
