### ISSUE TITLE
Consider moving repo to icxc with no password

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#25]
The revelation that the user/password is put into the distributed package files seems like grounds to reconsider the current idea of a password protected directory.

The main driver there was really JWST, but thinking harder makes me realize that in the end they are not really going to use that in production for very long.  What they will really want is to fork `skare3` and build their own.  In the meantime we could supply packages to them as needed, or just put non-private packages into a public area for them.

Overall it seems to be simpler and nicer to just have a publicly listed URL which has the requirement of Chandra VPN to actually use.

**Comment by jeanconn** [comment]
Not sure if it is grounds to run screaming away from the https plan.  I think we could stay with it for the meantime and move to icxc if/when jwst has moved to their own thing.

The idea that the packages shouldn't be publicly distributed after you have them  is not new, because the reason for the password is a few of them shouldn't be distributed publicly anyway.  But worth awareness that even the "could be public" packages right now have the password burned in.  I'll also see if there's a flag to just not burn in those details as I don't think they are helpful.

**Comment by taldcroft** [comment]
Plan to move to icxc is approved.  Will leave the cxc secure files in place for the moment and discuss with JWST.

**Comment by jeanconn** [comment]
OK.  I updated the docs and put the most recent builds in the icxc area.
