### ISSUE TITLE
Packages without recipe build dependences on setuptools_scm and git_archive will fail?

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#289]
For many of the packages, the meta.yaml in the package recipe does not include a setuptools_scm and setuptools_scm_git_archive dependence in the build dependencies.  ska_helpers has a setuptools_scm run dependence but not build dependence.

What this means, is that if setuptools_scm and setuptools_git_archive are not in the ska3build environment, they are pip downloaded as eggs in to the individual package repo.  They are then found and used when conda does the package build if needed.

If setuptools_scm and setutools_git_archive are in the ska3build environment, they are not pip downloaded and the conda build fails because they are also not in the build meta.yaml, so you just end up with unsatisfied dependencies.

I think the answer is just to add setuptools_git_archive to the ska_helpers run dependencies and then add ska_helpers to the build dependencies of all of the modules.  But then the question is if we should set the build dependencies in the meta.yaml by some environment variable or other process instead of doing this one edit in all the files this time.

**Comment by taldcroft** [comment]
> I think the answer is just to add setuptools_git_archive to the ska_helpers run dependencies and then add ska_helpers to the build dependencies of all of the modules.

This seems like an odd solution because ska_helpers is not actually a build dependency and it is not referenced in `setup.py`.  I just ran into this exact problem trying to build Ska.engarchive on Windows.  The current noarch Ska.engarchive packages fails on Windows because of the issue we discussed using `generic` instead of `python` for `noarch`.

>  if setuptools_scm and setuptools_git_archive are not in the ska3build environment, they are pip downloaded as eggs in to the individual package repo. They are then found and used when conda does the package build if needed.

At first glance I would think this is an OK solution, i.e. ensure these two packages are not in the ska3build environment.  But that didn't seem to work for me, at least on Windows.

I did however get a good build just tossing those two packages in as build dependencies.  Not clear on the best way to do this in bulk.  Maybe `ska_builder.py` can munge the `meta.yaml` file (or a copy) before it gets used.

**Comment by jeanconn** [comment]
> This seems like an odd solution because ska_helpers is not actually a build dependency and it is not referenced in setup.py. I just ran into this exact problem trying to build Ska.engarchive on Windows. The current noarch Ska.engarchive packages fails on Windows because of the issue we discussed using generic instead of python for noarch

A fair point.  It is really just a run dependence if you want to get the version.  I was thinking that ska_helpers also needed both of those scm packages, would be a lightweight thing to have in the build environment, and could be used as a placeholder for anything else we wanted as a build dependence, but might as well be explicit instead.

> At first glance I would think this is an OK solution, i.e. ensure these two packages are not in the ska3build environment. But that didn't seem to work for me, at least on Windows.

It worked to get them built for 2020.1, but I knew parts of that weren't reproducible, hence this issue.

> I did however get a good build just tossing those two packages in as build dependencies. Not clear on the best way to do this in bulk. Maybe ska_builder.py can munge the meta.yaml file (or a copy) before it gets used.

And that was on of my "another process" thoughts, though I would think adding a STD_BUILD_DEP jinja or some such could work.  Or just add these two setuptools packages to all of the recipes so it is explicit.

**Comment by javierggt** [comment]
Wouldn't it be easier to add setuptools_scm and setutools_git_archive to the ska_builder package?

**Comment by javierggt** [comment]
In my opinion, it is either that or add the dependency in all yaml files, but anyway packages will not build if ska_builder is not installed. So in what way is this different?

**Comment by taldcroft** [comment]
> Wouldn't it be easier to add setuptools_scm and setutools_git_archive to the ska_builder package?

If I didn't make a mistake, that doesn't actually work per Jean's initial description.  I used a ska_builder environment (a custom ska3) that had both of those packages installed.  Then I ran ska_builder.py from source (from its git repo) and got the failure that Jean reported.  One or both of us should have included a stack trace, but the upshot was that in the build process conda tries to do `python setup.py install` into the build env, and this fails because an internal attempt to `pip instal setuptools_scm_git_archive` results in pip saying that no packages match that package specification.  This was confusing to me, but that's what it said.

**Comment by taldcroft** [comment]
And to be concrete, I was using the shiny branch on windows building kadi.  I noticed that alot of the build dependencies still need cleanup post-SCM, e.g. numpy and six for Ska.engarchive.  Not a big deal of course.

**Comment by jeanconn** [comment]
> If I didn't make a mistake, that doesn't actually work per Jean's initial description. 

Yeah, I ran into the issue that if they are in the ska_builder environment, they don't get pip installed into the source directories and then they just aren't found in the "conda build" environment stage.  To add confusion, because our ska_builder.py process works out of a persistent git repo for each of the modules, if you don't delete that src directory (and you've already "fetched eggs" into the source directory at some point) you can see different behaviors later when you conda build; so if you add setuptools_scm to the ska_builder environment at that point it can look "fixed".

I've forgotten now at which stage the egg fetching happened.

And yeah, I had an action for myself to rebase shiny.

**Comment by javierggt** [comment]
I think at this point all packages have the corresponding files, and if there is any new one, it can be treated separately, so I am closing this.
