### ISSUE TITLE
conda wants to install skare3 packages even if a source-based version is already present

### ISSUE THREAD

**Issue by jzuhone** [sot/skare3#413]
**Description**
For a skare3 installation, conda seems to insist on installing "missing" packages even if a local source version of that package is installed in the same Python stack for development purposes.

**To Reproduce**
For any skare3 installation, install a package for development using, e.g.:
```
git clone https://github.com/acisops/dpa_check
cd dpa_check
pip install -e .
```
then (at any point later), update the ska3 core packages, conda will notice that `dpa_check` is not installed and try to install it from the skare3 package. This occurs even if the version of the pip-installed package is _later_ than the one provided by conda.

**Expected behavior**
Conda should recognize the pip installed version and not attempt to install the package from skare3. 

Not sure if there is a workaround or a setting we can fix. I've looked for the former but haven't found one.

**Comment by taldcroft** [comment]
Typically in this situation (playing with dev packages), I will force uninstall the meta-packages `ska3-flight` and/or `ska3-core`, and then conda uninstall any other packages that I plan to use in development.

Conda now warns that force uninstall is going away at some point, and I haven't looked into what that will imply.

I removed the Bug label because the behavior you describe is the intended behavior -- the package versions are supposed to be locked down by the meta-packages.

**Comment by taldcroft** [comment]
BTW, I mentioned uninstalling `ska3-core`, but in fact I don't think I have done that in normal dev work. Just know that there be dragons there...

**Comment by javierggt** [comment]
This is not a Ska bug, but a conda issue.

There are recent changes in conda to address this. See [Improving interoperability with pip](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/pip-interoperability.html) in conda docs. The bottomline is that what @jzuhone is requesting is an experimental feature present since conda 4.6 and not enabled by default, but one can do the following to enable it:
```
conda config --set pip_interop_enabled True
```

**Comment by javierggt** [comment]
In older versions, they discouraged using pip and conda together. This is what they said in their blog: [Using Pip in a Conda Environment](https://www.anaconda.com/blog/using-pip-in-a-conda-environment)

> Once pip is used to install software into a conda environment, conda will be unaware of these changes and may make modifications that would break the environment. Rather than running conda, pip and then conda again, a more reliable method is to create a new environment with the combined conda requirements and then run pip.
