### ISSUE TITLE
Still not sure about the ska_conda package/version

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#52]
Should the ska_conda Python package version track the ska3_builder conda package version (set by tag) or?

Will we really be building packages out of the ska_conda pkg data or out of the skare3 repo?

**Comment by taldcroft** [comment]
> Should the ska_conda Python package version track the ska3_builder conda package version (set by tag) or?

Not sure. Maybe if you explain to me why it would matter then the answer will become clear.

> Will we really be building packages out of the ska_conda pkg data or out of the skare3 repo?

We'll be doing whatever the maintainer's document says to be doing.  Does it basically work now, even if cumbersome?  If so, the answer for today if building packages out of ska_conda pkg data.

But I'm not wedded to current process.  If you think doing out of the repo ends up being simpler then I'm game to see a suggestion.

One imperfection / asymmetry I see in the current implementation and process is that all real packages have the version and changeable content defined in an external repo, but by contrast the ska3-* metapackages are defined in the builder repo.  Somehow the builder should be a thing which is maintained and versioned independently of the skare3 content.  Maybe that's where you were going?

It would feel better to update a file in `ska3-flight` and make a new release tag.  Maybe the meta-package build recipes could be special-cased and pulled in from github instead of living in the package.  I think that would vastly reduce the number of updates to ska_builder (skare3) and make this repo far more static.

**Comment by jeanconn** [comment]
> Not sure. Maybe if you explain to me why it would matter then the answer will become clear.

I don't know.  As you described an "asymmetry" for the metapackages, the ska_conda package is now installed in the builder environment with Python package version 0.1 and conda package version 2018.07.30 (or whatever it is at).  I don't know if we'll care.  It will feel weird to update a package and not have its Python package increment, but we shouldn't be doing much with it as a real Python package.

**Comment by jeanconn** [comment]
> One imperfection / asymmetry I see in the current implementation and process is that all real packages have the version and changeable content defined in an external repo, but by contrast the ska3-* metapackages are defined in the builder repo. Somehow the builder should be a thing which is maintained and versioned independently of the skare3 content. Maybe that's where you were going?

Yes.  we'd talked about maybe having a separate repo for the metapackages, but I don't know if it might just be better if they were built out of the skare3 repo itself instead of out of package data from ska3_builder.  I'm less concerned about elegance here and more concerned with the fact that making and installing a new version of the ska3_builder package into the build environment seems silly, especially if you've already built the new metapackage.  For current workflow:

1) package update happens outside of ska3_builder
2) running ska3_builder makes an updated version of that package
3) to get that package in ska3-flight, one edits the skare3 repo ska3-flight metapackage

Then what do you do to make a new ska3-flight?  

Do you

1) make the ska3-flight metapackage 

or

1) commit the change
2) tag the skare3 repo
3) build a new version of ska3_builder conda package
4) install the new ska3_builder
5) build the ska3-flight package from the pkg data in ska3_builder

The first path seems more intuitive.

**Comment by javierggt** [comment]
This seems outdated to me.
