### ISSUE TITLE
What should we use for the production build environment?

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#53]
For production, should the aca user build out of ska3/flight (after it is installed) or some other conda installation just for ska3_builder?  

I installed a conda installation to /proj/sot/ska/skare3_build for now.

**Comment by taldcroft** [comment]
> or some other conda installation just for ska3_builder?

It seems more simpler and safer to build using an dedicated not-flight environment.  Otherwise you need two sets of instructions, one if you happen to have a ska3/flight available, and another if you are starting from scratch.

> I installed a conda installation to /proj/sot/ska/skare3_build for now.

Thanks, but (since it is easy) can you instead install to `/proj/sot/ska3/test`?  I'm planning to send the path to a wide distribution and I want the path to look correct for a ska3 test environment.  You can delete what's there.

**Comment by jeanconn** [comment]
> I installed a conda installation to /proj/sot/ska/skare3_build for now.

I meant I installed a ska3_builder environment to /proj/sot/ska/skare3_build .  The plan was still to install a conda ska3-flight root environment in /proj/sot/ska/test  .

**Comment by jeanconn** [comment]
I think we've settled on moving to build out of the repo instead of the pkg data.  So open actions to:
 - [ ] update ska_conda / ska3_builder for that
 - [ ] update docs

**Comment by javierggt** [comment]
This is more than two years old. The context of "what to use for production build environment" has changed. We are using docker+actions to build.
