### ISSUE TITLE
Add jplephem

### ISSUE THREAD

**Issue by jeanconn** [sot/skare3#74]

**Comment by jeanconn** [comment]
This is in ska3-flight but we didn't add an ephemeris to SKA/data or ska_sync.

**Comment by jeanconn** [comment]
Also are there environment variables this would need to use SKA/data as a default source or?

**Comment by jeanconn** [comment]
Or for operational use are we just going to use @taldcroft 's horizon's query to check catalogs for planets etc?

**Comment by taldcroft** [comment]
We should plan on jplephem, since that is much faster, network-independent and can support things like "give me the jupiter position for the entire week at 5 minute intervals".

jplephem itself just needs to be given an ephemeris file so we just need to put one (probably the 11 Mb DE432S) in the right place and update the sync scripts.  But that only *needs* to happen when we have software that actually uses it.  I'm thinking a convenience method in `chandra_aca` that computes RA, Dec for a planet over a duration.

**Comment by taldcroft** [comment]
One slight loose end is getting the apparent magnitude of a planet.  For that we probably need Horizons for the definitive answer.

**Comment by jeanconn** [comment]
I also like extent.

**Comment by taldcroft** [comment]
BTW, jplephem is already in ska3-flight right?  We should close this issue?

**Comment by taldcroft** [comment]
Extent is easy enough to compute with ephemeris.  Mag is harder since it depends on phase.

**Comment by jeanconn** [comment]
Related to "already in ska3-flight" yes per my first comment.   I just wasn't sure if the other things-that-needed-to-be-done were tracked anywhere or if this was the only place before closing the issue.

**Comment by taldcroft** [comment]
Closing since jplephem has been added.  The way to *use* this package should be tracked elsewhere.
