### ISSUE TITLE
Remove nbpresent from ska3-core

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3#90]
The nbpresent jupyter extension is nothing but an annoyance to me (it shows a useless toolbar at the bottom and seems to take away the very useful toolbar at the top).  Since we never do notebook presentations, I suggest removing this from our core package list.

**Comment by jeanconn** [comment]
I merged #173 but then reverted it because actually removing the nbpresent package with conda tried to remove other packages (and we hadn't been explicit about them).   I don't have the record handy of which packages it *also* tried to remove, but we'll want to either straighten that out or let this issue be OBE with just a ska3-core update that will include the modern packages and will stop trying to support the CentOS5 builds.

**Comment by javierggt** [comment]
I was thinking about this...

Normally, jupyter extensions need to be enabled after extension, so one option is to not enable it. And perhaps @taldcroft can just disable it.

I checked and I do not see any nbpresent toolbar in jupyter. I see it listed in the conda packages, but I can't enable it:
```
(ska3) javierg agasc $ jupyter nbextension enable nbpresent
Enabling notebook extension nbpresent...
      - Validating: problems found:
        - require?  X nbpresent
```

I tried `jupyter nbextension install nbpresent --py` and got an error. It seems it tries to install it in a global location `/usr/local/share/jupyter/nbextensions` instead of the conda directory. In any case, it is not enabled by default.

**Comment by taldcroft** [comment]
For some reason this jupyter extension is automatically enabled for me when creating a new environment, so I need to specifically disable. Which I can do, for the record, with:
```
jupyter-nbextension disable nbpresent --py --sys-prefix
jupyter-serverextension disable nbpresent --py --sys-prefix
```
Anyway, :+1: on just letting this slide for now hoping it will be "OBE with just a ska3-core update that will include the modern packages (but not nbpresent)".

**Comment by jeanconn** [comment]
Done with shiny releases.
